mcrapet/plowshare-modules-legacy

1fichier.sh
This typo was reported by a debian user - see [BTS#780311](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780311).
=> Misspleling in module 1fichier.sh

multiup_org.sh
We not really use authentification for upload.
With this modification you can anonymous upload on multiup.org (test just now).
=> Add anonymous upload for multiup_org

multiup_org.sh
Hello,
Simple upload link with the website or plowup is given so:
http://www.multiup.org/download/XXX/FILENAME.ext
So I replace only download with en/mirror so we come on the page with the links.
I'm not sure about the rest of the code (cookie file, ...)
But it work with only this change.
=> Do plowlist work again with multiup_org

config, lunaticfiles.sh
This module support download for anonymous and free accounts, probe for %f, %s and %i. The website is partially translated into English, but free downloads are only allowed from Poland IP addresses. Appropriate warning in this matter is provided.
There is one thing with recaptcha that bother me. With this module always first recaptcha is impossible to resolve. It consist two graded words (instead only one graded word). It doesn't matter how hard I try it is always wrong. It is like antibot mechanism. Here it is example of this recaptcha:
When I reload it to another one then I can resolve it (it consist only one graded word), like in this example:
With my previous module catshare first recaptcha is ok. I don't know if I can do something with this at module level, or it can be done at core …
=> lunaticfiles: new module

mediafire.sh
After resolving captcha we are redirected to an error page, so once
again load a proper page. This change is strongly related and probably
fixes mcrapet/plowshare#14.
Extensively tested with this list of test files:
```
http://www.mediafire.com/download/6yy0i251xks40a8/Test_file_5MB.zip
http://www.mediafire.com/download/gbu13pdexeuf81m/Test_file_10MB.zip
http://www.mediafire.com/download/b9rr63o4nn0jgqj/Test_file_15MB.zip
http://www.mediafire.com/download/0kiv6b1l3hxsdll/Test_file_20MB.zip
http://www.mediafire.com/download/1ka2a22o03b6h46/Test_file_25MB.zip
http://www.mediafire.com/download/aegr29cmoncc7i5/Test_file_30MB.zip
http://www.mediafire.com/download/p5u6sf6n3fdju04/Test_file_35MB.zip
http://www.mediafire.com/download/pxch4aq4yyu37um/Test_file_40MB.zip …
```
=> mediafire (download): upstream updated

config, fileshark.sh
Added support for:
- download for anonymous
- probe for %f, %s and %i
Anonymous and free accounts are the same in terms of download speed,
so only anonymous downloads are implemented. Free downloads are only
allowed from Poland IP addresses. Appropriate warning in this matter
is provided.
=> fileshark: new module

zippyshare.sh
print() function doesn't work in javascript, replaced it with console.log(). I was getting the following error before the change:
```
plowdown "http://www.zippyshare.com/v/______/file.html"
Starting download (zippyshare): http://www.zippyshare.com/v/______/file.html
/tmp/plowdown.18044.28293.js:22
print(elts['fimage'].href);
^
ReferenceError: print is not defined
at Object.<anonymous> (/tmp/plowdown.18044.28293.js:22:9)
at Module._compile (module.js:446:26)
at Object..js (module.js:464:10)
at Module.load (module.js:353:32)
at Function._load (module.js:311:12)
at Array.0 (module.js:484:10)
at EventEmitter._tickCallback (node.js:190:39)
```
=> Update zippyshare.sh to fix Javascript error

1fichier.sh
Hello, it's a PR for https://github.com/mcrapet/plowshare-modules-legacy/issues/57
On line 251 I use a sed, it's maybe better to use the parse function but I don't how I can keep my '\' before the ' " '. Without any reason, I lost all my backslash apart these in the brackets.
When I do a plowup -H I see this for 1fichier, I'm not sure it's display normaly so I prefer to ask.
-d, --message=MESSAGE            Set file message (is send with notification email)
--domain=ID                  You can set domain ID to upload (ID can be found at http://www.1fichier.com/en/api/web.html)
--email-to=EMAIL             <To> field for notification email
--restrictip                 Restrict login session to my IP address
--folder=FOLDER              Folder to upload files into
Cheers.
=> Add --folder option for 1fichier

CONTRIBUTORS
The names are from the licenses of various files in this repository, and the emails are from the git commit history (and so are already public information distributed with this repository).
=> Add missing contributors

.mailmap
This file is used by [git-shortlog](https://git-scm.com/docs/git-shortlog) to tidy up the author and email information in the commit authorship data. This will make it easier to check contributions using `git shortlog -sne` for updating `CONTRIBUTORS` etc.
=> Add git mailmap

filecloud.sh, mediafire.sh
=> filecloud: find string not found for a file

uloz_to.sh
Hello,
I use "-L" in curl to avoir the moved permanently.
Maybe there is a best solution to pass properly curl options ?
I update the id for the downloadForm.
Cheers
=> uloz.to: Pass the moved permanently error and update the ID for downloadForm

jheberg.sh
Since few days jheberg is using https scheme instead of http. When using an http link, it is now allowing to follow link to https.
=> Updating jheberg.sh to handle https forwarding

openload.sh
Hello,
It fixes https://github.com/mcrapet/plowshare-modules-legacy/issues/141
But I'm not really happy that I force the embed link to have '/' at the end.
I don't find how allow in parse to have or not a end with '/'.
The other idea was to take all the string after embed and remove the '/' if it was there but I not found it really nice.
=> openload: Grab fid from URL if we use embed link

1fichier.sh
Hello,
1fichier change their warning message to wait between downloads.
I'm pretty sure that there's the same issue with other warning messages like [this one](https://github.com/mcrapet/plowshare-modules-legacy/blob/master/1fichier.sh#L159), but I can't reproduce.
I also fixed the access to the final download link, it's no longer available in `Location` header after clicking on `Access to download`.
This pull request should fix #145
Feel free to test.
Cheers,
=> 1fichier: fix download issue

1fichier.sh
Authenticated download fails when "force menu" is enabled in 1fichier preferences panel. Fix that.
=> 1fichier: fix authenticated download

rapidgator.sh
Note that this patch is applied partially over #170 [ace28b6262bdd](https://github.com/mcrapet/plowshare-modules-legacy/commit/ace28b6262bdd68aa6f8664785751ae6ac0002c0), as it is actually needed for this module to work.
=> rapidgator.sh: patched solvemedia captcha detection

1fichier.sh
It's quite annoying that whenever I run plowshare I get logged out of 1fichier in my browser. I added it as an option in case someone wants the old behavior, although I don't see why you would want to do that on a download/upload with plowshare.
=> 1fichier: Don't purge old sessions by default

mediafire.sh
It seems that they redirect http requests to https. I'm not familiar with the code, but it looks like this solves the issue.
=> Fix mediafire downloads

uptobox.sh
Proof with a premium account : 
```
$ plowdown http://uptobox.com/5ptsfgkkk9ha
Output directory: /tmp
uptobox: take --auth option from configuration file
Starting download (uptobox): http://uptobox.com/5ptsfgkkk9ha
Starting login process: XXXXX/************
File URL: https://www90.uptobox.com/dl/AAafkqj_se8VeidpgybvCmYAkEfFpxxzb46Na0jFJd1XSs7r5506a_UW31mxXnIMOowFeUAflmRF8-ysWT6aZotjl24Rq6x9_v2iNzx3umRTPOZ019bbzBEi6Om-Qz6DSqDwuTpzeYviuBxMGtBNFQ/LICENSE
Filename: LICENSE
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 35147  100 35147    0     0   193k      0 --:--:-- --:--:-- --:--:--  193k
/tmp/LICENSE
```
=> Fix #191 : uptobox : take into account a small ui changes

uptobox.sh
'Extend Premium' instead of 'Renew premium' for premium downloads.
=> fix download

uloz_to.sh
Czech variant of uloz.to switched to ulozto.cz as a default.
This PR adds this domain to the list.
Solves:
```
No module found, try simple redirection
Skip: no module for URL (https://ulozto.cz)
```
=> ulozto: New domain: ulozto.cz.

bayimg.sh
The download path is now rendered as a relative url in the Bayimg page source, code amended to include the hostname.
=> Fix to download url path

rapidgator.sh
The "MODULE_RAPIDGATOR_DOWNLOAD_SUCCESSIVE_INTERVAL" variable should be set to zero when user is logged into premium account.
=> successive download interval rapidgator premium

uptobox.sh
I  parse correctly the errors showed:
```
Starting download (uptobox): https://uptobox.com/c2h7k0m6rx0s
Starting login process: XXXX/******
Unexpected remote error: We detected that en email has already been sent to you. Please check your inbox
You are trying to log in from a different country, please check your mailbox to allow the connection.
Login process failed. Bad username/password or unexpected content
```
=> Show errors on up2box
