solidfiles.sh
=> Fix download link in solidfiles.sh

config, openload_io.sh
Anonymous download and probe support.
=> openload.io: new module

catshare.sh, config
This module adds download (anonymous and free users) and probe support. Premium download is not supported, because I don't have a premium account. This module was roughly tested be me, but this is my first plowshare module so fell free to review it.
=> catshare: new module

multiup_org.sh
It is a solution for my issue (https://github.com/mcrapet/plowshare-modules-legacy/issues/13)
I not know if it's good, but it work.
I think that the choice for favorite hosts is useless for anonymous.
So I use a if / else to skip this.
(Sorry for the merge pull request, I not know how avoid it).
If you know how, say it please ^^
=> Add DEFAULT_HOSTS when we do an anonymous upload with multiup_org

catshare.sh
I improved catshare module a bit. If you want I can squash commits into one.
=> catshare: various improvements

config, salefiles.sh
With the same warning about recaptcha as stated here: https://github.com/mcrapet/plowshare-modules-legacy/pull/34
=> added download support for salefiles.com

zippyshare.sh
=> zippyshare (download): upstream updated

4shared.sh
Fixes #12, also prefers filenames with extension.
=> 4shared (download): upstream updated

turbobit.sh
Fixes #28, also fixes probe.
Test file: http://turbobit.net/t26gjc1p08no.html
=> turbobit (download, probe): upstream updated

depositfiles.sh
Fixes #29.
Test file: http://dfiles.eu/files/ba6scyr4s
=> depositfiles (download): upstream updated

uploadable_ch.sh
Fixes #22, also fixes download and probe.
[Test file](https://www.uploadable.ch/file/6fB7G5FGKjkC/Test file 20MB.zip).
=> uploadable_ch (download, probe, upload): upstream updated

config, filejoker.sh
With the same warning about recaptcha as stated here: https://github.com/mcrapet/plowshare-modules-legacy/pull/34
=> added download support for filejoker.net

lunaticfiles.sh
Small fixes that I previously missed.
=> lunaticfiles (download): small fixes

config, fboom_me.sh
Added support for:
- download for anonymous
- probe for %f, %s and %i
=> fboom.me: new module

1fichier.sh
We can now create and upload subfolders.
Exemple --folder directory/subdirectory will create directory and subdirectory
if not exist and upload the file in subdirectory
I use echo "$NAME" | tr '/' '\n' to search the dir_id of each directory.
It's maybe possible with parse but I have difficult with regex.
Feel free to optimize, if it's possible.
Cheers.
=> 1fichier (upload): Create and upload in subfolders

1fichier.sh
Hello again ^^
If we try to upload a file with a folder that contain a "[" or "]" we have an error with the parse function.
To avoid the problem I replace this with '\[' and '\]' so it work with the match and parse function.
Cheers.
=> 1fichier (upload): replace [ and ] with compliant form for match and parse function

1fichier.sh
Hello with this modification we can now create directories that contant some symbol like "+".
Cheers.
=> 1fichier (upload): Convert the directory name with uri_encode_strict

config, espafiles.sh
Supports:
- download anonymous
- probe for %f %s %i
=> espafiles: new module

config, filedais.sh
Support anonymous downloading and probing for filedais.com and anafile.com
=> filedais: anon dl and probing for filedais/anafile

mediafire.sh
Mediafire now includes a hidden security field on their password
protected links.
Parse and include the required value in the POST.
Mediafire redirects to an error page after certain requests.
Re-request the original URL when this error occurs.
Related: #43
=> mediafire (download): fix password protected downloads

uploaded_net.sh
=> uploaded_net: create ref_auth cookie. Fixes #113.

mediafire.sh
Correct part of #109 (not the ID part which was not needed for me, but provide a test case/url and I will add it).
=> mediafire (download): handle new URL style

CONTRIBUTORS
Information reconstructed from `git shortlog -sne`, copyright headers, public github profiles and commit data
=> Add missing contributors

mediafire.sh
Fixes #109 
It appears to work without the second patch @PhunkyBob mentioned
=> handle mediafire.com/file/$hash/$filename

uptobox.sh
=> fix uptobox upload

openload.sh
Implements download for free user.
There is surely possibility to improve this PR but it's a first step.
Feel free to merge it and modify after.
Cheers.
Edit: it fix issue #104
=> Openload: Implement download file for free user through the API

CONTRIBUTORS
Add contributors from the last batch of merged pull requests.
=> Add new contributors

rapidgator.sh
When I'm trying to upload a file, I'm getting a random "**Unexpected state: processing**" error to almost every file. This should fix the problem https://github.com/mcrapet/plowshare-modules-legacy/issues/115. No more duplicate files 😄
=> Prevent "Unexpected state: processing" error

multiup_org.sh
fix the listing of multiup.org
=> multiup.org: fix listing

rapidgator.sh
=> rapidgator.sh: fix upload regex and add authentication to delete

catshare.sh
Fix for https://github.com/mcrapet/plowshare-modules-legacy/issues/117
=> fix catshare free/premium account recognition

uptobox.sh
fixing download for freeaccount #191 
havn't test on premium account as I havn't got one
=> uptobox (download): update (upstream changed)

uptobox.sh
The url of the login change a little, here is the modification to make it work again
=> uptobox: login page change

1fichier.sh
=> 1fichier : fix listing

uptobox.sh
Adapt to change in Uptobox my_account page
For issue #226
=> Uptobox : Detect account type

uptobox.sh
Needs to follow redirects to work now.
=> uptobox: Fix file upload

depositfiles.sh, filejoker.sh
For premium downloads, an additional form request needs to be submitted in order to generate the download link.
The download link itself can only used if appropriate cookie variables have been set (`joker_cook` and `xip`), otherwise the curl command will fail with 'Wrong IP' message.
This PR both allows the true download link to be generated and subsequently sets the cookie variables to allow the curl command to complete.
Should close #248.
=> filejoker update to handle premium accounts.

multiup_org.sh
Plowup couldn't find delete url and plowlist couldn't retrieve the urls
I removed the kind of language switch because I'm not sure it's needed anymore but if someone got an error I will look a bit further about it.
=> Fix muliup errors for plowup and plowlist

uptobox.sh
change the download url to `https`
=> uptobox : always download in https

config, pixeldrain.sh
Added basic module to support anonymous downloads from pixeldrain hoster. Download and probe function use pixeldrain hoster restful API's. Not cookies were used in any function at the moment.
=> Added basic plugin for pixeldrain download and probe

1fichier.sh
```
rep: Received 9 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:IP Locked
rep: === CURL END ===
```
=> Deals with IP Locked of 1fichier
